import random

# Sharp Tongue model pool based on observed Telegram collectible variants.
# weight is the displayed rarity percentage used as a relative random weight.
MODELS = [
    {"name":"Glitch","weight":0.5,"style":"glitch"},
    {"name":"Secret Look","weight":0.5,"style":"secret"},
    {"name":"Teasing Look","weight":0.5,"style":"teasing"},
    {"name":"Zombie Bite","weight":0.5,"style":"zombie"},
    {"name":"Acid Witch","weight":1.5,"style":"acid"},
    {"name":"Comics","weight":1.5,"style":"comics"},
    {"name":"Frostbite","weight":1.5,"style":"frost"},
    {"name":"Karlach","weight":1.5,"style":"fire"},
    {"name":"Melony","weight":1.5,"style":"melon"},
    {"name":"Neon Club","weight":1.5,"style":"neon"},
    {"name":"Pop Art","weight":1.5,"style":"pop"},
    {"name":"Punk Girl","weight":1.5,"style":"punk"},
    {"name":"Redlight","weight":1.5,"style":"red"},
    {"name":"Sweety","weight":1.5,"style":"sweet"},
    {"name":"Coral Reef","weight":2.0,"style":"coral"},
    {"name":"Devilfish","weight":2.0,"style":"devil"},
    {"name":"Ferrum Fatale","weight":2.0,"style":"metal"},
    {"name":"Galaxy","weight":2.0,"style":"galaxy"},
    {"name":"Golden Girl","weight":2.0,"style":"gold"},
    {"name":"High Voltage","weight":2.0,"style":"voltage"},
    {"name":"Leopard","weight":2.0,"style":"leopard"},
    {"name":"Lizard","weight":2.0,"style":"lizard"},
    {"name":"Minimalipstick","weight":2.0,"style":"minimal"},
    {"name":"Night Club","weight":2.0,"style":"night"},
    {"name":"Padme","weight":2.0,"style":"padme"},
    {"name":"Succubus","weight":2.0,"style":"succubus"},
    {"name":"Sweet Berry","weight":2.0,"style":"berry"},
    {"name":"Vampire","weight":2.0,"style":"vampire"},
    {"name":"Avatar","weight":2.5,"style":"avatar"},
    {"name":"Cold Bite","weight":2.5,"style":"cold"},
    {"name":"Daring Kiss","weight":2.5,"style":"daring"},
    {"name":"Femme Fatale","weight":2.5,"style":"femme"},
    {"name":"Glamour","weight":2.5,"style":"glamour"},
    {"name":"Glossy Hot","weight":2.5,"style":"glossy"},
    {"name":"Hot Summer","weight":2.5,"style":"summer"},
    {"name":"Hypnotic","weight":2.5,"style":"hypnotic"},
    {"name":"Lady Night","weight":2.5,"style":"lady"},
    {"name":"Manga Smile","weight":2.5,"style":"manga"},
    {"name":"Morticia","weight":2.5,"style":"morticia"},
    {"name":"Mystique","weight":2.5,"style":"mystique"},
    {"name":"Pepelicious","weight":2.5,"style":"pepe"},
    {"name":"Pink Mamba","weight":2.5,"style":"mamba"},
    {"name":"Queen","weight":2.5,"style":"queen"},
    {"name":"Rainbow","weight":2.5,"style":"rainbow"},
    {"name":"Sour Bite","weight":2.5,"style":"sour"},
    {"name":"Spicy Mint","weight":2.5,"style":"mint"},
    {"name":"Sunset","weight":2.5,"style":"sunset"},
    {"name":"Tangy Coil","weight":2.5,"style":"coil"},
    {"name":"Vegan Snake","weight":2.5,"style":"snake"},
    {"name":"Velvety","weight":2.5,"style":"velvet"},
]

BACKDROPS = [
    {"name":"Cappuccino","weight":1.0,"colors":["#4a3028","#b88a72"]},
    {"name":"Dark Lilac","weight":1.0,"colors":["#20142e","#77528f"]},
    {"name":"Emerald","weight":1.0,"colors":["#063d31","#21a578"]},
    {"name":"Fandango","weight":1.0,"colors":["#4f183d","#b63d88"]},
    {"name":"Khaki Green","weight":1.0,"colors":["#303622","#7f8e4f"]},
    {"name":"Mint Green","weight":1.0,"colors":["#153d34","#6fd8b5"]},
    {"name":"Pacific Cyan","weight":1.0,"colors":["#083a46","#22b8ce"]},
    {"name":"Persimmon","weight":1.0,"colors":["#4b2016","#e1684c"]},
    {"name":"Shamrock Green","weight":1.0,"colors":["#063b2a","#19b874"]},
    {"name":"Turquoise","weight":1.0,"colors":["#073d42","#24c6c9"]},
    {"name":"Aquamarine","weight":1.5,"colors":["#0b3a39","#5be0cb"]},
    {"name":"Black","weight":1.5,"colors":["#09090c","#34353c"]},
    {"name":"Burgundy","weight":1.5,"colors":["#35131d","#8d314d"]},
    {"name":"Caramel","weight":1.5,"colors":["#4d301e","#bb7e4f"]},
    {"name":"Chestnut","weight":1.5,"colors":["#3c241d","#8f5c48"]},
    {"name":"Chocolate","weight":1.5,"colors":["#2a1916","#765047"]},
    {"name":"Cobalt Blue","weight":1.5,"colors":["#101f4b","#355dc7"]},
    {"name":"Desert Sand","weight":1.5,"colors":["#4c3e31","#c1a57e"]},
    {"name":"Electric Indigo","weight":1.5,"colors":["#21115a","#6645e4"]},
    {"name":"Electric Purple","weight":1.5,"colors":["#3e145d","#a244d2"]},
    {"name":"French Blue","weight":1.5,"colors":["#102c50","#3b79c5"]},
    {"name":"Indigo Dye","weight":1.5,"colors":["#152b42","#315a85"]},
    {"name":"Jade Green","weight":1.5,"colors":["#12382f","#4f9d80"]},
    {"name":"Lavender","weight":1.5,"colors":["#342a4d","#9480ca"]},
    {"name":"Malachite","weight":1.5,"colors":["#0d3b2a","#39a768"]},
    {"name":"Moonstone","weight":1.5,"colors":["#29394a","#8eb0c5"]},
    {"name":"Mystic Pearl","weight":1.5,"colors":["#3c3650","#b7a9d1"]},
    {"name":"Onyx Black","weight":1.5,"colors":["#08080b","#25252d"]},
    {"name":"Purple","weight":1.5,"colors":["#2e1746","#7143a8"]},
    {"name":"Strawberry","weight":1.5,"colors":["#4c1928","#d84d72"]},
    {"name":"Amber","weight":2.0,"colors":["#4e3312","#d6922e"]},
    {"name":"Azure Blue","weight":2.0,"colors":["#123459","#3f91e8"]},
    {"name":"Battleship Grey","weight":2.0,"colors":["#2a2e34","#737b84"]},
    {"name":"Carrot Juice","weight":2.0,"colors":["#4f2a0d","#e7842d"]},
    {"name":"Copper","weight":2.0,"colors":["#4c291f","#b7654b"]},
    {"name":"Coral Red","weight":2.0,"colors":["#4b1d24","#df5f64"]},
    {"name":"Cyberpunk","weight":2.0,"colors":["#25103d","#a33ee9"]},
    {"name":"English Violet","weight":2.0,"colors":["#291b39","#6f4f85"]},
    {"name":"Grape","weight":2.0,"colors":["#301644","#7e3ca1"]},
    {"name":"Hunter Green","weight":2.0,"colors":["#102f23","#467a5e"]},
    {"name":"Ivory White","weight":2.0,"colors":["#69645a","#e7dfc7"]},
    {"name":"Lemongrass","weight":2.0,"colors":["#3a3c1a","#adb85d"]},
    {"name":"Light Olive","weight":2.0,"colors":["#38391f","#92945c"]},
    {"name":"Midnight Blue","weight":2.0,"colors":["#0b1731","#283c71"]},
    {"name":"Navy Blue","weight":2.0,"colors":["#091c37","#2a537e"]},
    {"name":"Neon Blue","weight":2.0,"colors":["#102359","#3c6ff0"]},
    {"name":"Orange","weight":2.0,"colors":["#54250c","#ed7b2b"]},
    {"name":"Pacific Green","weight":2.0,"colors":["#0a3d38","#34a799"]},
    {"name":"Pine Green","weight":2.0,"colors":["#0c3429","#39765d"]},
    {"name":"Pistachio","weight":2.0,"colors":["#34402c","#9fbd78"]},
    {"name":"Platinum","weight":2.0,"colors":["#373b43","#aeb6c5"]},
    {"name":"Pure Gold","weight":2.0,"colors":["#4e3a0f","#d7ad3f"]},
    {"name":"Raspberry","weight":2.0,"colors":["#4b1230","#c83770"]},
    {"name":"Roman Silver","weight":2.0,"colors":["#353944","#9298a8"]},
    {"name":"Rosewood","weight":2.0,"colors":["#421e26","#96515f"]},
    {"name":"Sapphire","weight":2.0,"colors":["#101d4a","#3555ba"]},
    {"name":"Satin Gold","weight":2.0,"colors":["#443612","#bd9c46"]},
    {"name":"Silver Blue","weight":2.0,"colors":["#263748","#718da6"]},
    {"name":"Sky Blue","weight":2.0,"colors":["#1b3b59","#69a9da"]},
    {"name":"Steel Grey","weight":2.0,"colors":["#29313a","#697682"]},
]

# Telegram calls this attribute a Pattern; the UI calls it "Узор".
# A broad pool of observed gift symbols/patterns is used for the game.
PATTERNS = [
    {"name":"Alkonost","weight":0.2,"icon":"🪽"},
    {"name":"Anchor","weight":0.2,"icon":"⚓"},
    {"name":"Apple","weight":0.2,"icon":"🍎"},
    {"name":"Axe","weight":0.2,"icon":"🪓"},
    {"name":"Ball","weight":0.2,"icon":"⚽"},
    {"name":"Bandage","weight":0.2,"icon":"🩹"},
    {"name":"Bishop","weight":0.2,"icon":"♝"},
    {"name":"Boat","weight":0.2,"icon":"⛵"},
    {"name":"Bone","weight":0.2,"icon":"🦴"},
    {"name":"Book","weight":0.2,"icon":"📖"},
    {"name":"Bottlenose","weight":0.2,"icon":"🐬"},
    {"name":"Brain","weight":0.2,"icon":"🧠"},
    {"name":"Bread","weight":0.2,"icon":"🍞"},
    {"name":"Broken Heart","weight":0.2,"icon":"💔"},
    {"name":"Bubble Tea","weight":0.2,"icon":"🧋"},
    {"name":"Bull of Heaven","weight":0.2,"icon":"🐂"},
    {"name":"Burger","weight":0.2,"icon":"🍔"},
    {"name":"Cap","weight":0.2,"icon":"🧢"},
    {"name":"Car","weight":0.2,"icon":"🚗"},
    {"name":"Celtic Cross","weight":0.2,"icon":"✣"},
    {"name":"Celtic Wolf","weight":0.2,"icon":"🐺"},
    {"name":"Chili Pepper","weight":0.2,"icon":"🌶️"},
    {"name":"Chocolate","weight":0.2,"icon":"🍫"},
    {"name":"Coat of Arms","weight":0.2,"icon":"🛡️"},
    {"name":"Cobra","weight":0.2,"icon":"🐍"},
    {"name":"Mushroom","weight":0.2,"icon":"🍄"},
    {"name":"Cute Bear","weight":0.4,"icon":"🧸"},
    {"name":"Heart Balloon","weight":0.6,"icon":"💗"},
    {"name":"Lips","weight":0.6,"icon":"💋"},
    {"name":"Shiny Heart","weight":0.6,"icon":"💖"},
    {"name":"Star Crown","weight":0.6,"icon":"👑"},
    {"name":"Illuminati","weight":0.8,"icon":"🔺"},
    {"name":"Coffin","weight":0.8,"icon":"⚰️"},
    {"name":"Blood Drop","weight":1.0,"icon":"🩸"},
    {"name":"Fish Skeleton","weight":1.2,"icon":"🐟"},
    {"name":"Lollipop","weight":1.2,"icon":"🍭"},
    {"name":"Moon","weight":1.2,"icon":"🌙"},
    {"name":"Nice Ghost","weight":1.2,"icon":"👻"},
    {"name":"Skull","weight":1.2,"icon":"💀"},
    {"name":"Lightning","weight":1.2,"icon":"⚡"},
    {"name":"Rose","weight":1.2,"icon":"🌹"},
    {"name":"Diamond","weight":1.2,"icon":"💎"},
    {"name":"Snake","weight":1.2,"icon":"🐍"},
    {"name":"Fire","weight":1.2,"icon":"🔥"},
    {"name":"Eye","weight":1.2,"icon":"👁️"},
    {"name":"Star","weight":1.2,"icon":"⭐"},
    {"name":"Cherry","weight":1.2,"icon":"🍒"},
    {"name":"Butterfly","weight":1.2,"icon":"🦋"},
]

def pick(pool):
    return random.choices(pool, weights=[x["weight"] for x in pool], k=1)[0]

def roll_traits():
    return pick(MODELS), pick(BACKDROPS), pick(PATTERNS)
